---
- name: Ensure postfix is installed.
  package:
    name: postfix
    state: present

- name: Update Postfix configuration.
  lineinfile:
    dest: "{{ postfix_config_file }}"
    line: "{{ item.option }} = {{ item.value }}"
    regexp: "^{{ item.option }}\\s*="
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postfix_config_options }}"
  notify: restart postfix

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: "{{ postfix_service_state }}"
    enabled: "{{ postfix_service_enabled }}"
